### ISSUE TITLE
Question about container registry access

### ISSUE THREAD

**Issue by kgibm** [ibm-cloud-docs/Registry#426]
Regarding this page: https://cloud.ibm.com/docs/Registry?topic=Registry-user#user

The implication I get from reading this is that the container registry is only accessible from within my managed namespace or resource group:

> Access to IBM Cloud Container Registry resources can be granted to the namespace resource by name, the resource group, or the entire service, that is, all namespaces in the account

What if I want anyone with an IBM Cloud account to access my container registry images?

**Comment by bainsy88** [comment]
@kgibm Opening namespace access up to everyone with a IBM cloud account is not something which is currently possible.

**Comment by kgibm** [comment]
Thank you
