### ISSUE TITLE
Docker toolbox is no longer supported

### ISSUE THREAD

**Issue by cncook001** [ibm-cloud-docs/Registry#431]
This page "https://cloud.ibm.com/docs/Registry?topic=Registry-getting-started" step 3. Click on the "Docker Toolbox" link. It is no longer supported. Please updated this section.

**Comment by SueGraham** [comment]
@cncook001 Many thanks for letting me know - I'll update the links to Docker Desktop.

**Comment by SueGraham** [comment]
The docs are updated, many thanks for your input. 
https://cloud.ibm.com/docs/Registry?topic=Registry-getting-started#gs_registry_images_pulling
