### ISSUE TITLE
Repository and digest are big

### ISSUE THREAD

**Issue by SimpleSamples** [ibm-cloud-docs/Registry#432]
These instructions are nearly perfect. The thing I needed to understand is that although the repository and digest names/ids (the first and second columns of the output of the `ibmcloud cr image-digests` command) are big, they just need to be concatenated together with an `@` sign between them to remove the corresponding image.

**Comment by SueGraham** [comment]
@SimpleSamples 

Hi, 

Thanks for your feedback.

There is information about the format in many topics, usually in the form of a tip:
![image](https://user-images.githubusercontent.com/26408909/169305243-e3225bfc-8f6f-4f9e-b700-75b5222a1275.png)

For example,
https://cloud.ibm.com/docs/Registry?topic=Registry-registry_images_#registry_images_remove_cli

Please can you let me know what topic you were using when you had a problem, or whether the tip isn't comprehensive enough, then I can update it to make it easier to use.

Many thanks

Sue

**Comment by SimpleSamples** [comment]
I am sorry but I assumed that the relevant documentation was indicated by this posting. I cannot find it now. It is the documentation that is linked to using a shortened link when we do a Code Engine build and we exceed our storage quota. And yes I think the documentation isn't comprehensive enough. A little more explanation would help a lot.

**Comment by SueGraham** [comment]
@SimpleSamples Sorry not to get back to you sooner, but I've been on vacation.

Was this the page you went to? 
https://cloud.ibm.com/docs/Registry?topic=Registry-registry_quota#registry_quota_freeup

Many thanks
Sue

**Comment by SueGraham** [comment]
@SimpleSamples 

I've updated the page to hopefully make what is required clearer: https://cloud.ibm.com/docs/Registry?topic=Registry-registry_quota#registry_quota_freeup

I hope this helps:

![image](https://user-images.githubusercontent.com/26408909/172452552-83d09f44-25ff-47cc-b9d3-eb6723788a27.png)


Regards

Sue
