### ISSUE TITLE
Add Knative as example for untagged images of Container Registry FAQ

### ISSUE THREAD

**Issue by HeavyWombat** [ibm-cloud-docs/Registry#434]
In the [Container Registry FAQ](https://cloud.ibm.com/docs/Registry?topic=Registry-registry_faq), there are two examples of why you might have untagged images. I would like to suggest to add Code Engine (Knative) as an example in either the first entry or as a separate entry if that makes no sense.

Background: For consistency reasons, when using IBM Cloud Code Engine, the underlying Knative implementation does resolve the image digest of a given image and uses the image with its digest internally. When someone overwrites the the image tag, Knative can reliably serve the original version since it is using the digest, however, this means that users most certainly have untagged images in their namespaces.

Idea: Extend the first entry in _Do I need untagged images?_ to something like this:
> The image was deployed by referencing the image by using the digest, for example [IBM Code Engine](https://cloud.ibm.com/docs/codeengine?topic=codeengine-deploy-app) does resolve and use an image digest when serving applications.

**Comment by SueGraham** [comment]
Thank you for your suggestion. The team are looking into it.
