### ISSUE TITLE
IBM container registry login with podman

### ISSUE THREAD

**Issue by sharma-sudhakar** [ibm-cloud-docs/Registry#435]
Step 5:
1. `ibmcloud cr login --client podman` not working giving below result.

Result:

> Incorrect Usage: flag provided but not defined: -client
>
>NAME:
>login - Log the local Docker client in to IBM Cloud Container Registry.
>
>USAGE:
>   ibmcloud cr login

**Comment by kemarsh** [comment]
@sharma-sudhakar could you ensure you have the latest version of the IBM Cloud CLI installed please. If the `--client` flag still doesn't work for you after updating can you provide the output from running:

`ibmcloud plugin list`
